using OpenPlexus.Graph;
using OpenPlexus.Worlds;
using Xunit.Abstractions;

namespace OpenPlexus.Tests;

/// <summary>
/// The binding world's experiment, on scenes generated in 2017 by people who had
/// never heard of this project.
/// </summary>
/// <remarks>
/// <b>Fork 25 built a world specifically to fail and then lifted it.</b> Every
/// one of those numbers was taken on scenes generated by the same hands that
/// built the mechanism. CLEVR is fifteen thousand scenes of exactly that
/// confusion — two objects whose attributes can be swapped without changing the
/// code set — and it ships the scene graph as JSON, so no vision is needed and
/// none is claimed.
/// </remarks>
public sealed class ClevrTests(ITestOutputHelper output)
{
    /// <summary>
    /// Where the corpus is, or a failure that says how to get it.
    /// </summary>
    /// <remarks>
    /// <b>Fails rather than skipping</b>, which is this suite's standing rule —
    /// see <see cref="Tree"/>.
    /// </remarks>
    private static string Corpus
    {
        get
        {
            var corpus = Path.Combine(Tree.Repo(), "corpora", "CLEVR_v1.0");

            Assert.True(File.Exists(Path.Combine(corpus, "scenes", "CLEVR_val_scenes.json")),
                $"the CLEVR corpus is not at {corpus}. Fetch it with:\n"
                + "    bash corpora/fetch.sh");

            return corpus;
        }
    }

    private static ClevrSettings World(
        int scenes = 120, bool segmented = true, bool tagged = true, bool fleeting = false) => new()
    {
        Corpus = Corpus, Scenes = scenes, Segmented = segmented, Tagged = tagged, Fleeting = fleeting,
    };

    private static WalkSettings Dials => Fixture.Dials(stamina: 8.0);

    // ---- what the corpus is, asserted rather than described -----------------

    [Fact]
    public void A_scene_is_its_objects_and_every_object_has_four_attributes()
    {
        var world = new Clevr(World(scenes: 20));

        Assert.Equal(20, world.Scenes.Count);

        foreach (var scene in world.Scenes)
        {
            // FOUR ATTRIBUTES AND AN INDEX PER OBJECT, PLUS ONE FOR THE SCENE, so
            // the code count is one more than a multiple of five.
            Assert.Equal(1, scene.Codes.Length % 5);

            Assert.NotNull(scene.Groups);
            Assert.Single(scene.Codes.Where(code => code.Modality == Clevr.Where));

            // AND THE SCENE INDEX IS ALWAYS FLEETING, whatever the object arm
            // says, or every attribute grows a row entry per scene forever.
            Assert.Contains(Clevr.Seen(scene.Scene), scene.Fleeting!);
        }

        output.WriteLine(
            $"scenes={world.Scenes.Count} asked={world.Asked} chance={world.Chance:F4} " +
            $"codes={world.Scenes.Sum(scene => scene.Codes.Length)}");
    }

    [Fact]
    public void An_index_is_fresh_for_every_object_of_every_scene()
    {
        // An index that came back in a later scene would name a KIND of object,
        // which is the one thing it must not do -- and object 0 of every scene
        // sharing a code would be a hub joining every scene to every other.
        var world = new Clevr(World(scenes: 30));
        var seen = new HashSet<OpenPlexus.Codes.Code>();

        foreach (var code in world.Scenes
                     .SelectMany(scene => scene.Codes)
                     .Where(code => code.Modality == Clevr.Object))
            Assert.True(seen.Add(code), "an object index came back in another scene");
    }

    [Fact]
    public void Only_the_questions_this_architecture_can_answer_are_kept()
    {
        var world = new Clevr(World(scenes: 60));

        Assert.True(world.Asked > 0, "no answerable question was found at all");

        foreach (var scene in world.Scenes)
            foreach (var question in world.About(scene.Scene))
            {
                // A CONJUNCTION, not a single filter -- one filter names a class
                // and the answer is then whatever is commonest, which measures the
                // corpus rather than the binding.
                Assert.True(question.Origins.Length >= 2);

                // AND THE FILTERS NAME A DIFFERENT ATTRIBUTE FROM THE ANSWER, or
                // the question would contain its own answer.
                Assert.DoesNotContain(question.Origins, code => code.Modality == question.Asking);
            }
    }

    [Fact]
    public void Turning_segmentation_off_changes_the_grouping_and_nothing_else()
    {
        // THE CEILING ARM HAS TO DIFFER IN ONE THING. If the flat world emitted
        // different codes as well, a drop would have two explanations.
        var segmented = new Clevr(World(scenes: 20));
        var flat = new Clevr(World(scenes: 20, segmented: false));

        Assert.Equal(
            segmented.Scenes.Select(scene => scene.Codes.AsEnumerable()),
            flat.Scenes.Select(scene => scene.Codes.AsEnumerable()));

        Assert.All(segmented.Scenes, scene => Assert.NotNull(scene.Groups));
        Assert.All(flat.Scenes, scene => Assert.Null(scene.Groups));
    }

    // ---- what the graph does with it ---------------------------------------

    /// <summary>Enough scenes to put a few hundred questions behind an arm.</summary>
    /// <remarks>
    /// <b>Most of CLEVR is thrown away</b> — see <see cref="Clevr"/> — so a scene
    /// yields well under one answerable question on average.
    /// </remarks>
    private const int Scenes = 700;

    private async Task<ClevrResult> RunAsync(Refer refer, Pricing pricing, int scenes = Scenes)
    {
        using var run = new ClevrRun(
            World(scenes),
            Dials with { Pricing = pricing, Accumulate = Accumulate.Agreement },
            seed: 1);

        var result = await run.RunAsync(refer);
        output.WriteLine($"pricing={pricing,-8} {result}");
        return result;
    }

    [Fact]
    public async Task Finding_the_object_and_reading_it_want_opposite_pricing()
    {
        // THE BEST-OF-BOTH-WORLDS CASE, AND IT IS SHARPER THAN THE USUAL ONE.
        // The recurring fault in this design is a dial two WORLDS want different
        // values of. This is one QUESTION whose two hops want different values,
        // which no per-world default can fix.
        //
        // The arithmetic says why, and it is not subtle. An object index is seen
        // exactly once, an attribute is seen in most scenes. Receiver pricing
        // charges `seen(receiver)`, so attribute-to-index is the cheapest hop in
        // the graph and index-to-attribute is among the dearest; sender pricing
        // charges `seen(sender)` and inverts precisely that pair. The reference
        // half of the task is the first hop and the answer half is the second.
        var finding = await RunAsync(Refer.Conjunction, Pricing.Receiver);
        var reading = await RunAsync(Refer.Conjunction, Pricing.Sender);

        Assert.True(finding.Reference > reading.Reference,
            $"receiver did not win the reference: {finding.Reference} against {reading.Reference}");

        Assert.True(reading.Accuracy > finding.Accuracy,
            $"sender did not win the answer: {reading.Accuracy} against {finding.Accuracy}");

        // AND NEITHER WINS BOTH, which is the whole point. Stated as a crossover
        // rather than two separate wins, because two arms each winning something
        // is only interesting if no arm wins everything.
        Assert.True(finding.Accuracy < reading.Accuracy && reading.Reference < finding.Reference,
            "one pricing won both halves, so there is nothing to split");
    }

    [Fact]
    public async Task The_ceiling_arm_shows_the_second_hop_is_the_one_that_starves()
    {
        // HANDED THE OBJECT ITSELF, so the reference is perfect by construction
        // and the only thing left is reading an attribute off it. Receiver pricing
        // still cannot, and that is the second hop being unaffordable rather than
        // the walk failing to refer.
        var dear = await RunAsync(Refer.Index, Pricing.Receiver);
        var cheap = await RunAsync(Refer.Index, Pricing.Sender);

        Assert.Equal(1.0, dear.Reference, 6);
        Assert.Equal(1.0, cheap.Reference, 6);

        Assert.True(cheap.Accuracy > dear.Accuracy * 2,
            $"the second hop was not the difference: {cheap.Accuracy} against {dear.Accuracy}");

        // THE STARVATION IS VISIBLE AS SILENCE, not as a wrong answer. A walk that
        // cannot afford the hop reaches nothing in the modality it was narrowing
        // to, which is a different failure from reaching the wrong thing.
        Assert.True(dear.Silent > cheap.Silent,
            $"the dear arm was not the silent one: {dear.Silent} against {cheap.Silent}");
    }

    [Fact]
    public async Task An_index_the_walk_must_arrive_at_cannot_be_fleeting_so_the_rows_grow()
    {
        // THE COST THIS WORLD CANNOT AVOID, AND IT IS THE ROW-GROWTH TRAP FROM
        // OUTSIDE. Everywhere else an index is declared fleeting, which keeps it
        // out of every lasting node's row. Here the question does NOT know which
        // object it means -- it knows two attributes of one -- so the walk has to
        // be able to ARRIVE at an index, and a fleeting index cannot be arrived
        // at. The row therefore grows by one entry per object forever.
        //
        // Read `Widest` and never the mean: the growth mints a great many tiny
        // index nodes, and they hold `Edges / Nodes` flat while the handful of
        // attribute nodes the walk actually passes through grow without bound.
        var few = await RunAsync(Refer.Conjunction, Pricing.Receiver, scenes: 100);
        var many = await RunAsync(Refer.Conjunction, Pricing.Receiver, scenes: 400);

        Assert.True(many.Widest > few.Widest * 3,
            $"the widest row did not grow with the corpus: {many.Widest} against {few.Widest}");

        // AND THE MEAN CANNOT SEE IT, which is why the trap is written down.
        var thin = few.Edges / (double)few.Nodes;
        var thick = many.Edges / (double)many.Nodes;

        Assert.True(thick < thin * 3,
            $"the mean fan-out grew as fast as the widest row, so this world no "
            + $"longer demonstrates the trap: {thick} against {thin}");
    }
}
