using OpenPlexus.Codes;
using OpenPlexus.Commitments;
using OpenPlexus.Machines;
using OpenPlexus.Worlds;
using Xunit.Abstractions;

namespace OpenPlexus.Tests;

/// <summary>
/// The binding world's experiment, on scenes generated in 2017 by people who had
/// never heard of this project.
/// </summary>
/// <remarks>
/// <b>Fork 25 built a world specifically to fail and then lifted it.</b> Every
/// one of those numbers was taken on scenes generated by the same hands that
/// built the mechanism. CLEVR is fifteen thousand scenes of exactly that
/// confusion — two objects whose attributes can be swapped without changing the
/// code set — and it ships the scene graph as JSON, so no vision is needed and
/// none is claimed.
/// </remarks>
public sealed class ClevrTests(ITestOutputHelper output)
{
    /// <summary>
    /// Where the corpus is, or a failure that says how to get it.
    /// </summary>
    /// <remarks>
    /// <b>Fails rather than skipping</b>, which is this suite's standing rule —
    /// see <see cref="Tree"/>.
    /// </remarks>
    private static string Corpus
    {
        get
        {
            var corpus = Path.Combine(Tree.Repo(), "corpora", "CLEVR_v1.0");

            Assert.True(File.Exists(Path.Combine(corpus, "scenes", "CLEVR_val_scenes.json")),
                $"the CLEVR corpus is not at {corpus}. Fetch it with:\n"
                + "    bash corpora/fetch.sh");

            return corpus;
        }
    }

    private static ClevrSettings World(
        int scenes = 120, bool segmented = true, bool tagged = true, bool fleeting = false) => new()
    {
        Corpus = Corpus, Scenes = scenes, Segmented = segmented, Tagged = tagged, Fleeting = fleeting,
    };

    // ---- what the corpus is, asserted rather than described -----------------

    [Fact]
    public void A_scene_is_its_objects_and_every_object_has_four_attributes()
    {
        var world = new Clevr(World(scenes: 20));

        Assert.Equal(20, world.Scenes.Count);

        foreach (var scene in world.Scenes)
        {
            // Four attributes and an index per object, plus one for the scene, so
            // the code count is one more than a multiple of five.
            Assert.Equal(1, scene.Codes.Length % 5);

            Assert.NotNull(scene.Groups);
            Assert.Single(scene.Codes.Where(code => code.Modality == Clevr.Where));

            // And the scene index is always fleeting, whatever the object arm
            // says, or every attribute grows a row entry per scene forever.
            Assert.Contains(Clevr.Seen(scene.Scene), scene.Fleeting!);
        }

        output.WriteLine(
            $"scenes={world.Scenes.Count} asked={world.Asked} chance={world.Chance:F4} " +
            $"codes={world.Scenes.Sum(scene => scene.Codes.Length)}");
    }

    [Fact]
    public void An_index_is_fresh_for_every_object_of_every_scene()
    {
        // An index that came back in a later scene would name a KIND of object,
        // which is the one thing it must not do -- and object 0 of every scene
        // sharing a code would be a hub joining every scene to every other.
        var world = new Clevr(World(scenes: 30));
        var seen = new HashSet<OpenPlexus.Codes.Code>();

        foreach (var code in world.Scenes
                     .SelectMany(scene => scene.Codes)
                     .Where(code => code.Modality == Clevr.Object))
            Assert.True(seen.Add(code), "an object index came back in another scene");
    }

    [Fact]
    public void Only_the_questions_this_architecture_can_answer_are_kept()
    {
        var world = new Clevr(World(scenes: 60));

        Assert.True(world.Asked > 0, "no answerable question was found at all");

        foreach (var scene in world.Scenes)
            foreach (var question in world.About(scene.Scene))
            {
                // A CONJUNCTION, not a single filter -- one filter names a class
                // and the answer is then whatever is commonest, which measures the
                // corpus rather than the binding.
                Assert.True(question.Origins.Length >= 2);

                // And the filters name a different attribute from the answer, or
                // the question would contain its own answer.
                Assert.DoesNotContain(question.Origins, code => code.Modality == question.Asking);
            }
    }

    /// <summary>
    /// A round puts a question the scene on its own does not carry.
    /// </summary>
    /// <remarks>
    /// <b>The check that tells a hard problem from an empty one.</b> If the filters were
    /// re-stated as their own attribute codes, the moment would
    /// be identical whether the question referred by size or the scene merely happened to
    /// hold a large thing — so a population would be scored on a question nobody put, and
    /// what came back would be chance either way. That is the failure the walk had on this
    /// world, and it read as the architecture failing for as long as it went unchecked.
    /// </remarks>
    [Fact]
    public void A_round_puts_a_question_the_scene_alone_does_not_carry()
    {
        var world = new Clevr(World(scenes: 200));
        var scenes = world.Scenes.ToDictionary(one => Clevr.Seen(one.Scene));

        for (var round = 0; round < 200; round++)
        {
            var codes = world.Next().Seen.Codes.ToList();

            // Which picture, and it is what makes the rest of the moment checkable at all.
            var scene = scenes[Assert.Single(codes, code => code.Modality == Clevr.Where)];

            Assert.Single(codes, code => code.Modality == Clevr.Asks);

            var refers = codes.Where(code => code.Modality == Clevr.Refers).ToList();

            Assert.True(refers.Count >= 2,
                "a reference of fewer than two filters is not a conjunction");

            Assert.Equal(refers.Count, refers.Distinct().Count());

            // Derived rather than re-stated, which is the whole content of the modality.
            Assert.Empty(refers.Intersect(scene.Codes));

            // And nothing else is added, so the moment is the scene plus the question.
            Assert.Equal(scene.Codes.Length, codes.Count - refers.Count - 1);
        }
    }

    // ---- what the graph does with it ---------------------------------------

    /// <summary>Enough scenes to put a few hundred questions behind an arm.</summary>
    /// <remarks>
    /// <b>Most of CLEVR is thrown away</b> — see <see cref="Clevr"/> — so a scene
    /// yields well under one answerable question on average.
    /// </remarks>
    private const int Scenes = 3000;

    /// <summary>
    /// CLEVR reaches the commitment learner, the held-back questions are answered at chance,
    /// and 93% of the table is codes that can never fire again.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The runner a standing objection asked for. This world had a <c>ClevrRun</c> driven by
    /// the walk, so when the walk went the scenes survived and the thing that turned them
    /// into a measurement did not.
    /// </para>
    /// <para>
    /// <b>A round is one question rather than one scene.</b> A commitment expects one code
    /// and CLEVR asks several things about a picture, so the moment is the scene's codes,
    /// one <see cref="Clevr.Refers"/> code per filter of the question's chain, and one
    /// <see cref="Clevr.Asks"/> code saying which attribute is wanted. The filters never
    /// name the attribute being queried, which
    /// <see cref="Only_the_questions_this_architecture_can_answer_are_kept"/> asserts.
    /// </para>
    /// <para>
    /// <b><see cref="Clevr.Chance"/> is the bar and <c>Tally</c>'s is not.</b> The tally
    /// divides one by <see cref="Clevr.Outcomes"/>, a blind guess over all fifteen attribute
    /// values at once; the questions ask for one attribute each and do not divide evenly
    /// between the four, so the guesser to beat is the weighted one the world computes.
    /// </para>
    /// <para>
    /// <b>The withheld set sits on that bar under both arms.</b> The population answers every
    /// one of the three hundred held-back questions and gets them right at the rate a
    /// weighted blind guess does. Nothing composed, and the harness did ask — over a hundred
    /// distinct commitments take a seat on those questions.
    /// </para>
    /// <para>
    /// <b>This is fork 25's ceiling on scenes nobody here generated.</b> That fork built a
    /// world to fail at attribute binding and lifted it with grouping and a per-object index,
    /// on scenes generated by the same hands that built the mechanism. The lift cannot arrive
    /// here: the channel carrying it is
    /// <see cref="Codes.IQuantizer{TObservation}.Bind"/>, which has had no reader since the
    /// walk went. A conjunctive scope over an unsegmented bag cannot say <i>the one that is
    /// large and also metal</i>, which is rung four's claim.
    /// </para>
    /// <para>
    /// <b>And the arm is what a fleeting mark is worth.</b> This world
    /// mints eleven codes a scene that can never be seen again, and
    /// <see cref="ClevrSettings.Fleeting"/> is whether it says so. Told, the table falls by
    /// 90% and holds no per-scene row at all; not told, 93% of it is rows nothing will ever
    /// read.
    /// </para>
    /// <para>
    /// <b>The kill line fired, and taught more than a pass would.</b> It was written
    /// before the run: the mark reaches the table and nothing else, so the arm dies if any
    /// other count moves. Repairs go from 3,169 to 18,733 and minted from 178 to 1,418, so
    /// it died. The table is not a cache — it is repair's candidate set, and there is no such
    /// thing as changing one without the other. What the numbers say is that most of what
    /// repair was ranking were codes that could not fire again, and the budget it spent on
    /// them is why it found so little.
    /// </para>
    /// <para>
    /// <b>So the mark is a soundness rule wearing a footprint optimisation's clothes.</b> A
    /// child built on a code that cannot recur can never fire, so it is dead on the round it
    /// is minted. That is worth having on its own terms and it is not what this was built
    /// for, which is why the arm has to run on a second world before anything is concluded.
    /// </para>
    /// </remarks>
    [Fact]
    public void Clevr_reaches_the_commitment_learner()
    {
        var told = Learnt(fleeting: true);
        var silent = Learnt(fleeting: false);

        // The second world `Spanning` owes, and it is the one that says what the dial costs
        // where a grouping exists and the question does not sit inside one. The corpus
        // segments the SCENE and leaves the question's codes in no part, so a scope naming a
        // referring filter and an attribute of one object is refused wherever the two came
        // from different objects -- which is the mechanism doing what it says on a world
        // nobody generated for it.
        var spanning = Learnt(fleeting: true, spanning: Spanning.Anything);

        foreach (var (arm, run) in new[]
                 { ("told", told), ("silent", silent), ("told, spanning", spanning) })
        {
            output.WriteLine(
                $"{arm} | chance {run.World.Chance:F3} | drawn {run.Tally.Recent:F3} | held "
                + $"{run.Tally.Resident}, {run.Tally.Repaired} repairs, {run.Tally.Minted} "
                + $"minted | table {run.Rows} rows, {run.Once} per-scene");

            output.WriteLine(
                $"{arm} | withheld {run.Unseen.Right}/{run.Unseen.Answered} answered of "
                + $"{run.Unseen.Asked} = {run.Composed:F3}, {run.Unseen.Deciders} deciders");
        }

        // The harness asked, which is the reading's precondition and not a result. A moment
        // that carried no question would return chance too, and that is the failure the walk
        // had on this world for as long as nobody checked.
        Assert.True(told.Unseen.Answered > 0 && silent.Unseen.Answered > 0,
            "nothing fired on a withheld question, so this run asked nothing");

        Assert.True(told.Tally.Recent > told.World.Chance,
            $"{told.Tally.Recent:F3} is under the {told.World.Chance:F3} a weighted blind "
            + "guess scores, so the question is not reaching the learner");

        // What the mark buys, and it is the table.
        Assert.Equal(0, told.Once);

        Assert.True(silent.Once > silent.Rows / 2,
            $"{silent.Once} of {silent.Rows} rows are per-scene codes, which is under half. "
            + "Untold, this world writes eleven such rows a scene, so a drop here means the "
            + "moment changed rather than the learner");

        Assert.True(told.Rows * 2 < silent.Rows,
            $"{told.Rows} rows told against {silent.Rows} silent, which is not the fall the "
            + "mark is for");

        // The reading, and it is an upper bar rather than a target. Three standard errors of
        // the weighted chance over however many were answered, so the width is the sample's
        // and not a constant somebody chose. Going red means the withheld set moved off the
        // bar, which is the day something composed -- take the number and raise this.
        foreach (var run in new[] { told, silent, spanning })
        {
            var spread = 3.0 * Math.Sqrt(
                run.World.Chance * (1.0 - run.World.Chance) / run.Unseen.Answered);

            Assert.True(run.Composed < run.World.Chance + spread,
                $"{run.Composed:F3} on the withheld set is more than three standard errors "
                + $"({spread:F3}) above the {run.World.Chance:F3} bar, so something "
                + "composed. This assertion records a null result and closing it is "
                + "progress.");
        }
    }

    /// <summary>One arm of the fleeting question, run whole.</summary>
    /// <param name="World">The corpus, for its bars.</param>
    /// <param name="Tally">What the run scored.</param>
    /// <param name="Unseen">What it scored on the questions it was never shown.</param>
    /// <param name="Rows">Separation rows across the whole population.</param>
    /// <param name="Once">How many of those are codes minted for one scene.</param>
    private sealed record Run(
        Clevr World, Tally Tally, Examined Unseen, long Rows, long Once)
    {
        /// <summary>What share of the answered withheld questions were right.</summary>
        public double Composed =>
            Unseen.Answered == 0 ? 0.0 : Unseen.Right / (double)Unseen.Answered;
    }

    /// <param name="fleeting">Whether the world says its per-scene indexes cannot recur.</param>
    /// <param name="spanning">Whether a scope may be about more than one of the objects.</param>
    private static Run Learnt(bool fleeting, Spanning spanning = Spanning.Thing)
    {
        var world = new Clevr(
            World(scenes: Scenes, fleeting: fleeting) with { Withheld = 300 });

        var brain = new Brain(
            new CommittingSettings { Capacity = 4000, Spanning = spanning }, seed: 1);

        var tally = new Bench(new Watching<Coded>(world, new Passthrough<Coded>(one => one)), brain)
            .Run(rounds: 20_000, sweep: 1000, target: 0.9, window: 2000);

        // An object index and a scene index are minted fresh every scene, so every row they
        // write is a row nothing will ever read. This is fork 31's question -- the table is
        // what blows up -- asked on the world that makes it sharp.
        var rows = brain.Held.All.Sum(one => (long)one.Separations.Count);

        var once = brain.Held.All.Sum(one => (long)one.Separations.Keys.Count(code =>
            code.Modality == Clevr.Object || code.Modality == Clevr.Where));

        Assert.NotNull(tally.Unseen);

        return new Run(world, tally, tally.Unseen, rows, once);
    }
}
