"""Generate a docker-compose file for an N-node distributed run, and say why.

## What a container buys over a subprocess

`openplexus/node_main.py` already runs a node as its own OS process, and that measured
**0.28 ms per step exact** on loopback. So the process boundary is not what is missing.

What is missing is latency. `docs/SCALE.md` records that the binding constraint is hop
latency — ten sequential hops at ~50 ms round trip is ~500 ms against `d_max`'s 640 ms,
about 20% headroom — and loopback is roughly **180x faster than that**. A loopback run
sails through a constraint that is really tight, and proves nothing about C2.

**`tc netem` is the reason for the container.** It needs `NET_ADMIN`, which compose can
grant and a subprocess cannot get without touching the host's own stack.

## It launches `openplexus.node_main`, not a tool of its own

The node entry point already exists and sizes itself against cgroup limits. An earlier
version of this generator launched a duplicate under `tools/`; that duplicate is deleted
and this passes the `OPENPLEXUS_*` contract `node_main` documents.

## Node count

Dimension splitting gives each node `d_model / nodes` dimensions, and `g4-01` measured
that a lone node needs **16** to hold a standalone opinion (0.949, falling to 0.412 at
four). So `--nodes` beyond `d_model / 16` still runs and still divides the arithmetic
exactly; it just describes nodes that cannot answer alone. `note 081` is why that ceiling
matters and why concept partitioning is the fix — **which this harness does NOT exercise,
because `ConceptStore` has no socket transport yet.** Stated so a number from here is not
read as a number about the arrangement the project chose.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from openplexus.distributed import slices_for  # noqa: E402

#: `tc` on the loopback-facing interface, then exec the node. Applied per node so a
#: heterogeneous network is expressible -- which is the realistic case and the one
#: `d_max` exists for.
NETEM = ("tc qdisc add dev eth0 root netem delay {delay}ms {jitter}ms "
         "2>/dev/null || echo 'netem unavailable, running at loopback speed'; ")


def compose(nodes: int, d_model: int, vocab: int, seed: int, steps: int,
            port: int, delay: float, jitter: float, windows: list[int],
            deadline: float | None) -> str:
    slices = slices_for(d_model, nodes)
    shared = [f"      OPENPLEXUS_NODES: '{nodes}'",
              f"      OPENPLEXUS_D_MODEL: '{d_model}'",
              f"      OPENPLEXUS_VOCAB_SIZE: '{vocab}'",
              f"      OPENPLEXUS_SEED: '{seed}'",
              f"      OPENPLEXUS_DRIVER_PORT: '{port}'",
              # Without this an untrained `wo` is zeros, the bar predicts one token
              # forever, and the exactness check passes whatever the nodes send.
              "      OPENPLEXUS_DECODER: '1'"]
    lines = ["# GENERATED by tools/cluster_compose.py -- edit that, not this.",
             "services:",
             "  driver:",
             "    image: openplexus-cluster",
             "    command: >",
             f"      python tools/cluster_driver.py --steps {steps}",
             f"      --windows {' '.join(str(w) for w in windows)}"
             + (f" --deadline {deadline}" if deadline else ""),
             "    environment:",
             "      BIND_HOST: 0.0.0.0",
             *shared,
             "    networks: [plexus]"]
    for index, own in enumerate(slices):
        prefix = NETEM.format(delay=delay, jitter=jitter) if delay else ""
        # `node_main` exits 2 if the driver is not listening yet, and compose starts
        # everything at once, so restart is what makes startup order not a
        # correctness requirement.
        lines += [
            f"  node{index}:  # slice [{own.lo}, {own.hi})",
            "    image: openplexus-cluster",
            "    depends_on: [driver]",
            "    restart: on-failure",
            f'    command: ["/bin/sh", "-c", "{prefix}exec python -m '
            f'openplexus.node_main"]',
            "    environment:",
            "      OPENPLEXUS_DRIVER_HOST: driver",
            f"      OPENPLEXUS_NODE_INDEX: '{index}'",
            *shared,
            "    networks: [plexus]"]
        if delay:
            lines.append("    cap_add: [NET_ADMIN]")
    lines += ["networks:", "  plexus:", "    driver: bridge", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--nodes", type=int, default=4)
    parser.add_argument("--d-model", type=int, default=64)
    parser.add_argument("--vocab", type=int, default=64)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--steps", type=int, default=64)
    parser.add_argument("--port", type=int, default=9099)
    parser.add_argument("--delay", type=float, default=0.0,
                        help="one-way netem delay in ms. 0 disables netem")
    parser.add_argument("--jitter", type=float, default=0.0)
    parser.add_argument("--windows", type=int, nargs="+", default=[1, 4])
    parser.add_argument("--deadline", type=float, default=None)
    parser.add_argument("--out", type=Path,
                        default=ROOT / "docker-compose.cluster.yml")
    args = parser.parse_args()

    if args.nodes > args.d_model:
        raise SystemExit(
            f"{args.nodes} nodes cannot split {args.d_model} dimensions -- some "
            f"node would own nothing, and a node with an empty slice is not a "
            f"thin node, it is a bug waiting to look like one")
    per_node = args.d_model // args.nodes
    args.out.write_text(compose(
        args.nodes, args.d_model, args.vocab, args.seed, args.steps, args.port,
        args.delay, args.jitter, args.windows, args.deadline), encoding="utf-8")
    print(f"wrote {args.out}: {args.nodes} nodes x {per_node} dims of "
          f"{args.d_model}")
    if per_node < 16:
        print(f"  NOTE {per_node} dims per node is below g4-01's 16, so these "
              f"nodes cannot hold a standalone opinion. The split stays exact; "
              f"the nodes are just thin (note 081).")
    print(f"  netem: {'%g ms +/- %g' % (args.delay, args.jitter) if args.delay else 'OFF (loopback speed)'}")
    print(f"\n  docker compose -f {args.out.name} up --abort-on-container-exit")
    return 0


if __name__ == "__main__":
    sys.exit(main())
